export const actionTypes = {
    NEW_ROUND: 'NEW_ROUND',
    PLAY_CARD: 'PLAY_CARD',
    FINISH_PLAY: 'FINISH_PLAY',
    IS_STORY_TELLER: 'IS_STORY_TELLER',
    SUBMIT_STORY :'SUBMIT_STORY',
    CLEAR_STORY: 'CLEAR_STORY'
};