export const actionTypes = {
    START_CLIENT : 'START_CLIENT',
    START_GAME: 'START_GAME',
    NEW_ROUND: 'NEW_ROUND',
    PLAY_CARD: 'PLAY_CARD',
    UPDATE_PLAY: 'UPDATE_PLAY',
    REVEAL_PLAY: 'REVEAL_PLAY',
    IS_STORY_TELLER: 'IS_STORY_TELLER',
    SUBMIT_STORY: 'SUBMIT_STORY',
    CLEAR_STORY: 'CLEAR_STORY',
    REGISTER_PLAYER: 'REGISTER_PLAYER',
    UPDATE_PLAYERS: 'UPDATE_PLAYERS',
};